name: Build
on:
  push:
    branches:
      - main
jobs:
    # Prepare python 3.10
    build3101:
        name: Build (Python 3.10.1)
        runs-on: windows-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
            - name: Package
              run: |
                  pwsh -File scripts/package.ps1
                  dir
            - name: Upload
              uses: actions/upload-artifact@v2
              with:
                  name: package
                  path: package
            


    
